AWS_ACCESS_KEY: "AKIAYVZMZTVN3RP3ONXD"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "bryan-roof-estate"


SECRET_KEY: "sk_test_Rb4ZZWjY2eXjHTLZ8kDPUfCQ00Kxhoaogu"
PUBLISHABLE_KEY: "pk_test_YnFHIK1q9mPhPpi6KcM87PLU00AF1qRQqE"